spring:
  datasource:
    url: jdbc:h2:mem:testdb;
    schema: schema.sql
    username: sa
    password: 1
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    show-sql: true

    shell:
      interactive:
        enabled: false